### ISSUE TITLE
Refine talks query

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/rk-community-site#13]
There should be better way of doing this, but my brain only has this working version:
- add a "talks" field in the frontmatter of meetup markdowns
  + array of number, each an issue number for a talk
- home page: query only talks referenced by the nearest scheduled meetup
- meetup pages (still under construction) will query their corresponding talks

**Comment by thchia** [comment]
I think having the talks field in meetup frontmatter is good. When a talk is confirmed the frontmatter is updated and we redeploy. Otherwise we might end up with unconfirmed or cancelled talks being shown.

**Comment by wgao19** [comment]
Agreed. I now am also leaning towards maintaining some essential information for meetups via md files.
