### ISSUE TITLE
Text in Reaching Out block overflows container at certain viewports

### ISSUE THREAD

**Issue by huijing** [react-knowledgeable/rk-community-site#24]
Because `white-space: nowrap` is set on `.reachingOutList`, the text overflows the container when viewport is between 640px and 805px (i.e. iPad portrait orientation). For aesthetic reasons, we should keep `white-space: nowrap`. Suggest additional media queries to ensure text always stays within container.

![](https://i.imgur.com/wv6Td10.png)

**Comment by thchia** [comment]
Closed via #25
