### ISSUE TITLE
Add sponsors (a list similar with venue + venue logo) and rename venue sponsor -> venue

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/rk-community-site#27]
to prepare for
- a rare situation where we got more sponsors
- want to do a rk x gatsby session

**Comment by thchia** [comment]
Perhaps we can think about `venue` vs `sponsor`? I think right now we use them interchangeably, but in the proposed situation, we would still have one `venue` with multiple `sponsor`s.

**Comment by wgao19** [comment]
makes sense

**Comment by wgao19** [comment]
closing because it's done
