### ISSUE TITLE
⛱ this happened in react

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/rk-community-site#31]
Every month, we start our event by briefing everyone with a small [what happened in react](https://github.com/react-knowledgeable/react-knowledgeable-talks/issues/17) section. The slides are generated from [meetup markdown files like this](https://github.com/react-knowledgeable/rk-community-site/blob/master/content/meetups/2.md#%EF%B8%8F-react-updates-%EF%B8%8F).

For [hacktoberfest 2019](https://hacktoberfest.digitalocean.com/), we invite everybody to edit our meetup markdown for [november](https://github.com/react-knowledgeable/rk-community-site/blob/master/content/meetups/4.md)! Simply PR to add what you think is an interesting happening in React recently.

Popular kids can try to be funny too.

**Comment by Ta2Rim** [comment]
I love it!

**Comment by wgao19** [comment]
@Ta2Rim feel free to PR even if you're not in Singapore :P
