### ISSUE TITLE
make home page less clumsy

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/rk-community-site#55]
spinoff from #52, the home page looks very clumsy on wide screen, because we put a lot of content there. maybe we can optimize a little bit.

to elaborate, it's a lot of words, and if you scroll to the bottom, the left (topics) and right (stories) sections do not have very clear distinction:

![image](https://user-images.githubusercontent.com/2055384/67658060-7cc05900-f993-11e9-883a-259d2499fcc9.png)

**Comment by huijing** [comment]
Homepage at 1805px after update:

![Screenshot 2019-10-28 at 12 47 45 AM](https://user-images.githubusercontent.com/1461498/67663064-e6a01a80-f921-11e9-8422-cc7fab5b4b31.png)

**Comment by wgao19** [comment]
thanks @huijing ! closing since our eyes are happy now
