### ISSUE TITLE
unable to run site on local machine

### ISSUE THREAD

**Issue by huijing** [react-knowledgeable/rk-community-site#67]
1. Updated local to commit e5f0fc1.
2. Run `env GITHUB_TOKEN=<...> npm start`
3. Receive following error:
    ```
    > rk-community-site@1.0.0 start /Users/huijing/Sites/rk-community-site
    > npm run develop


    > rk-community-site@1.0.0 develop /Users/huijing/Sites/rk-community-site
    > gatsby develop

    The above error occurred in the <StoreStateProvider> component:
        in StoreStateProvider
        in App

    React will try to recreate this component tree from scratch using the error boundary you provided, App.
    Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! rk-community-site@1.0.0 develop: `gatsby develop`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the rk-community-site@1.0.0 develop script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/huijing/.npm/_logs/2019-10-31T05_14_23_784Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! rk-community-site@1.0.0 start: `npm run develop`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the rk-community-site@1.0.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/huijing/.npm/_logs/2019-10-31T05_14_23_803Z-debug.log

**Comment by thchia** [comment]
So somehow errors are being swallowed in react-redux (I faced a similar issue before in a different project).

There will be a more descriptive error deep inside somewhere that describes what React thinks is going wrong (in my case last time it was multiple copies of React)

**Comment by huijing** [comment]
Question is does this only happen on my machine or can it be replicated?

**Comment by thchia** [comment]
Hmm this happened to me:

- Pulled latest
- Ran `npm i`
- Ran `GITHUB_TOKEN=<xxx> npm start`
- Got same error

THEN realised I should be using yarn:

- Ran `yarn`
- Ran `GITHUB_TOKEN=<xxx> yarn start`
- ???
- Success

Now running `GITHUB_TOKEN=<xxx> npm start` also works.

Did you run `npm i`? That might have changed some things and npm and yarn have differing resolution strategies which _can_ cause issues like the multiple React one.

@huijing

**Comment by huijing** [comment]
I did run `npm i` and got the error like you. Running `yarn` did solve it.
Will add this to the README file for now.
Can dig into the reason why later ba.

**Comment by thchia** [comment]
@wgao19 I’m pretty sure the command ran. The problem was the “multiple React” / “hooks can’t be called in xyz” one which suggests to me it was a resolution problem in node_modules. Should be easily reproducible anyway

**Comment by wgao19** [comment]
oh i see, makes sense! thanks for figuring this out!
