### ISSUE TITLE
slides is broken 😨😱

### ISSUE THREAD

**Issue by wgao19** [react-knowledgeable/rk-community-site#70]
slides is broken because css is broken, which in turn is due to #63, i remember seeing some error around the `onInitialClientRender` call of a css in js injecting plugin

gonna spend some time and try to figure out this weekend, otherwise we may need to temporarily revert back to our era mode react again

**Comment by thchia** [comment]
What css specifically is broken? I think this is to do with the use of `callback` in the `replaceHydrateFunction` (like super high-level, very far away guess).

**Comment by thchia** [comment]
@wgao19 sorry I don't have time to try right now, but looking through the source code, I notice that `createRoot` accepts this in the second parameter:

```js
type RootOptions = {
  hydrate?: boolean,
  hydrationOptions?: {
    onHydrated?: (suspenseNode: Comment) => void,
    onDeleted?: (suspenseNode: Comment) => void,
  },
};
```

Perhaps we can try toggling the `hydrate` flag, and maybe calling `callback` at `onHydrated`?

#noideawhatimdoing

**Comment by wgao19** [comment]
my understanding is that the plugin that injects css in js doesn’t get to call onInitialClientRender based on our current patch :(

**Comment by thchia** [comment]
@wgao19 yeah - I think if the callback in the hydrate function isn’t called properly, then onInitialClientRender also won’t be called properly and perhaps the plugin doesn’t run.
