### ISSUE TITLE
Unsightly gap between "On the next RK" and "Stories" section

### ISSUE THREAD

**Issue by huijing** [react-knowledgeable/rk-community-site#83]
There is a very large gap between the "On the next RK" section and the "Stories" section, evident when the main content only takes up 2 columns.

![Screenshot_2019-11-17_at_6_18_27_AM](https://user-images.githubusercontent.com/1461498/68999917-838f1b80-0902-11ea-8072-40e13d76eca9.png)

**Comment by thchia** [comment]
Closed in #84
